apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: ggg-v1-0-0
    applicationId: app_34ba40d8-7ed9-4ec2-8380-18d942d48454
    version: v1.0.0
    organizationId: org_6d1064c7-007d-44b1-9606-8fef3a204121
    projectId: project_ccdb790d-12f2-4861-a3fd-fb3840651d3f
  name: ggg-v1-0-0
spec:
  selector:
    app: ggg-v1-0-0
